-- Projects
CREATE TABLE Projects1 (
 MID INTEGER NOT NULL,
 MN VARCHAR(50) NOT NULL,
 PRIMARY KEY (MID)
);

CREATE TABLE Projects2 (
 ID INTEGER NOT NULL,
 MID INTEGER NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (MID) REFERENCES Projects1 (MID)
);

CREATE TABLE Projects3 (
 PID INTEGER NOT NULL,
 PN VARCHAR(50) NOT NULL,
 PRIMARY KEY (PID)
);

CREATE TABLE Projects4 (
 SID INTEGER NOT NULL,
 SN VARCHAR(50) NOT NULL,
 PRIMARY KEY (SID)
);

CREATE TABLE Projects0 (
 ID INTEGER NOT NULL,
 PID INTEGER NOT NULL,
 SID INTEGER NOT NULL,
 PRIMARY KEY (ID, PID, SID),
 FOREIGN KEY (ID) REFERENCES Projects2 (ID),
 FOREIGN KEY (PID) REFERENCES Projects3 (PID),
 FOREIGN KEY (SID) REFERENCES Projects4 (SID)
);

INSERT INTO Projects1
SELECT DISTINCT MID, MN
FROM Projects;

INSERT INTO Projects2
SELECT DISTINCT ID, MID
FROM Projects;

INSERT INTO Projects3
SELECT DISTINCT PID, PN
FROM Projects;

INSERT INTO Projects4
SELECT DISTINCT SID, SN
FROM Projects;

INSERT INTO Projects0
SELECT DISTINCT ID, PID, SID
FROM Projects;


-- Shows
CREATE TABLE Shows1(
    UID INTEGER NOT NULL, 
    UN VARCHAR(50) NOT NULL,
    PRIMARY KEY (UID)
);

CREATE TABLE Shows2(
    SID INTEGER NOT NULL, 
    TI VARCHAR(50) NOT NULL,
    RA CHAR(5) NOT NULL,
    IMDB FLOAT,
    PRIMARY KEY (SID)
);

CREATE TABLE Shows0(
    UID INTEGER NOT NULL, 
    SID INTEGER NOT NULL, 
    S INTEGER NOT NULL,
    PRIMARY KEY (UID, SID),
    FOREIGN KEY (UID) REFERENCES Shows1 (UID),
    FOREIGN KEY (SID) REFERENCES Shows2 (SID)
);


-- Rentals
CREATE TABLE Rentals1(
    PID INTEGER NOT NULL,
    HID INTEGER NOT NULL,
    PN VARCHAR(50) NOT NULL,
    PRIMARY KEY (PID)
);

CREATE TABLE Rentals2(
    HID INTEGER NOT NULL,
    HS VARCHAR(50) NOT NULL,
    HZ INTEGER NOT NULL,
    PRIMARY KEY (HID)
);

CREATE TABLE Rentals3(
    HZ INTEGER NOT NULL,
    HC VARCHAR(50) NOT NULL
);

CREATE TABLE Rentals0(
    PID INTEGER NOT NULL,
    HID INTEGER NOT NULL,
    S INTEGER NOT NULL,
    PRIMARY KEY (PID, HID),
    FOREIGN KEY (PID) REFERENCES Rentals1 (PID),
    FOREIGN KEY (HID) REFERENCES Rentals1 (HID)
);


-- Matches
CREATE TABLE Matches1(
    HID INTEGER NOT NULL,
    HN VARCHAR NOT NULL,
    PRIMARY KEY (HID)
);

CREATE TABLE Matches2(
    AID INTEGER NOT NULL,
    AN VARCHAR NOT NULL,
    PRIMARY KEY (AID)
);

CREATE TABLE Matches3(
    RID INTEGER NOT NULL,
    RN VARCHAR NOT NULL,
    PRIMARY KEY (RID)
);

CREATE TABLE Matches0(
    MID INTEGER NOT NULL,
    HID INTEGER NOT NULL,
    AID INTEGER NOT NULL,
    RID INTEGER NOT NULL,
    D DATE NOT NULL,
    H INT,
    A INT,
    PRIMARY KEY (MID),
    FOREIGN KEY (HID) REFERENCES Matches1 (HID),
    FOREIGN KEY (MID) REFERENCES Matches2 (MID),
    FOREIGN KEY (RID) REFERENCES Matches3 (RID)
);